/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/(site)/page.tsx",
  "./components/sidebar.tsx",
  "./components/box.tsx",
  "./components/sidebaritems.tsx",
"./components/library.tsx",
"./components/header.tsx",
"./components/button.tsx",
"./components/listitems.tsx",
"./components/modal.tsx",
"./components/uploadmodal.tsx",
"./app/(site)/components/songitem.tsx",
"./app/(site)/components/pagecontent.tsx",
"./components/mediaitem.tsx",
"./app/search/page.tsx",
"./components/searchinput.tsx",
"./app/search/components/searchcontent.tsx",
"./components/likebutton.tsx",
"./actions/getLikedSongs.ts",
"./app/liked/page.tsx",
"./components/player.tsx",
"./components/playercontent.tsx",
"./components/slider.tsx"],
  theme: {
    extend: {},
  },
  plugins: [],
}

